targets:
  $default:
    builders:
      flutter_gen_runner:
        options:
          output: lib/gen/
          integrations:
            image: true
            flutter_svg: true
          parse_metadata: true
